parameters:
#    app.example.class: AppBundle\Example

services:
#    app.example:
#        class: %app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    app.event.weather_listener:
        class: AppBundle\Event\WeatherListener
        arguments:
            messageSender: "@app.message.message_sender"

    app.integration.yahoo_client:
        class: AppBundle\Integration\YahooClient

    app.message.message_sender:
        class: AppBundle\Message\MessageSender